
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Principal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TCELDA = 5;
  public static final int TETIQUETA_TABLA = 3;
  public static final int TFIN_FILA = 6;
  public static final int error = 1;
  public static final int TDOLAR = 2;
  public static final int TCELDA_ENCABEZADO = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TDOLAR",
  "TETIQUETA_TABLA",
  "TCELDA_ENCABEZADO",
  "TCELDA",
  "TFIN_FILA"
  };
}

